version: '3'
services:
    postgres-db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    
    api:
        depends_on:
            - postgres-db
        image: sajnaar/simple_blog_api
        build:
            context: ./
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        environment:
            - POSTGRES_HOST=postgres-db
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
        