--Drop tables
DROP TABLE episodeIV;

--For Episode IV
CREATE TABLE episodeIV (name STRING, line STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' TBLPROPERTIES ("skip.header.line.count"="2");
LOAD DATA LOCAL INPATH '/root/inputs/episodeIV_dialogues.txt' INTO TABLE episode IV;
INSERT OVERWRITE LOCAL DIRECTORY /root/HiveOutput2'

SELECT COUNT(*) FROM episode IV WHERE line LIKE '%Luke%';
